# Generated by Django 5.0 on 2023-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='color',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
