# Generated by Django 5.0 on 2023-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
