# Generated by Django 5.0 on 2023-12-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixoapi', '0002_collectible_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectible',
            name='condition',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
